### ISSUE TITLE
master branch contains the solution

### ISSUE THREAD

**Issue by ddhogan** [learn-co-curriculum/intro-to-redux-library-codealong#11]
This codealong appears to have all the code already completed in the master branch.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @ddhogan.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
