### ISSUE TITLE
App won't render in browser with code provided in readme

### ISSUE THREAD

**Issue by DGMarkel** [learn-co-curriculum/intro-to-redux-library-codealong#13]
Using the code the readme provides for index.js errors out with the following:

React.Children.only expected to receive a single React element child.

I had to remove line 15: `{' '}` to get the page to render.  

Full working code:

`
ReactDOM.render(
    <Provider store={store}>
        {' '}
        <App />
    </Provider>,
    document.getElementById('root')
);
`

**Comment by PetyaDjanovska** [comment]
Same issue March 15, 2019!
