### ISSUE TITLE
Same issue as #13 and #16 - ReactDOM.render Error

### ISSUE THREAD

**Issue by aburk3** [learn-co-curriculum/intro-to-redux-library-codealong#17]
Solution is: 
```
ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById("root")
);
```
Recreating issue to hopefully bump this, as this issue has persisted since January.

**Comment by maxwellbenton** [comment]
Hi @aburk3,

Thank you for opening this issue and providing a solution. We've updated this lesson and confirmed that is is no longer producing an error. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
