### ISSUE TITLE
Props has some issues

### ISSUE THREAD

**Issue by hankeliu2015** [learn-co-curriculum/intro-to-redux-library-codealong#21]
TypeError: Cannot read property 'length' of undefined
App.render
src/App.js:14
  11 | 	return (
  12 | 		<div className="App">
  13 | 			<button onClick={this.handleOnClick}>Click</button>
> 14 | 			 <p>{this.props.items.length}</p>
  15 | 		</div>
  16 | 	);
  17 | }

**Comment by maxwellbenton** [comment]
Hi @hankeliu2015,

Thank you for opening this issue. Unfortunately, I am unable to replicate the issue you experienced in `App`. It looks like the issue may be related to the Redux store not fully being set up, as `items` should be coming from there and appears not to be in your code example. However, we have recently updated this lesson's code snippets as well as the solution and confirmed that using the provided code in the Readme will produce a working application.

We apologize for any frustration this may have caused you, but appreciate your feedback and help in improving this lesson for future students!
