### ISSUE TITLE
This lab probably set to the wrong order

### ISSUE THREAD

**Issue by hankeliu2015** [learn-co-curriculum/intro-to-redux-library-codealong#22]
Go for this one first <https://github.com/learn-co-students/map-state-to-props-readme-online-web-pt-092418>. It should make sense. Good luck!

**Comment by maxwellbenton** [comment]
Hi @hankeliu2015,

Thanks for reporting this issue. We're now aware of it and are tracking this and other ordering issues in a new issue [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3). 

We are currently updating and restructuring the materials in this section and will add this to our internal work queue.  We will be updating the order of lessons in the next phase of this process and will take this information into consideration in upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
