### ISSUE TITLE
npm install react-redux

### ISSUE THREAD

**Issue by DanL12186** [learn-co-curriculum/intro-to-redux-library-codealong#3]
This codealong imports react-redux... I couldn't get it to work until I tried `npm install react-redux --save` (the readme mentioned using `npm install react --save`)

**Comment by marcnjaramillo** [comment]
I had the same problem. Looking at the `/.node_modules` you can see that this particular module is missing. I did the same thing you did to include that module to get it working. I hope they can update this soon so that other people won't have the same issue.

**Comment by bmolina-nyc** [comment]
The lab still does not have react-redux pre-bundled

Also think Provider should be discussed - it was introduced in this lab with no mention other than its place in the code.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
