### ISSUE TITLE
Extra ")" causing compiling to fail

### ISSUE THREAD

**Issue by jrodden1** [learn-co-curriculum/intro-to-redux-library-codealong#31]
After copying and pasting the updated code from the second to last code block in the lesson into `shoppingListItemReducer`, I get a compiler error:

```
Failed to compile.

./src/reducers/shoppingListItemReducer.js
Syntax error: Unexpected token, expected ; (17:4)

  15 |                  ...state,
  16 |                  items: state.items.concat(state.items.length + 1)
> 17 |           });
     |            ^
  18 |   
  19 |    default:
  20 |           console.log('Initial state.items length: %s', state.items.length);
```

It looks like there is an extra `)` on line 17.  

This should take you to the exact element on the page (line 17 in that code block) 
`document.querySelector("#js--region-body-content > div > div:nth-child(2) > div > div > div > div > pre:nth-child(29) > code > ol > li:nth-child(17) > span")`

**Comment by maxwellbenton** [comment]
Hi @jrodden1,

I've corrected the code snippet and removed the extra `)`. Thanks for spotting this and helping to improve our curriculum!
