### ISSUE TITLE
mocha test wrappers just take in .first and .last instead of by name

### ISSUE THREAD

**Issue by EricLum** [learn-co-curriculum/intro-to-redux-library-codealong#6]
Noticed that if you switch the order of the userinput and hometown input the tests don't pass because of lines like these: 

let usernameInput = wrapper.find('input').first(); // this line just takes the first input
    usernameInput.simulate('change', { target: { value: 'Bob', name: 'username' } });
    let hometownInput = wrapper.find({ type: 'text' }).last(); //this line just takes the last input.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @EricLum! We've actually removed the tests for this lesson and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
