### ISSUE TITLE
Provider dependency still causing issues

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/intro-to-redux-library-codealong#8]
Students need to do the command: npm install react-redux --save
This is not stated explicitly in the readme. Please edit.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and included react-redux in the package.json file and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
