### ISSUE TITLE
Lesson not working

### ISSUE THREAD

**Issue by Dalynn4** [learn-co-curriculum/intro-to-redux-library-codealong#9]
Tried to open this lesson and this pulls up in IDE
// ♥ learn open intro-to-redux-library-codealong-v-000
Looking for lesson...
/usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/lib/learn_open/lessons/ios_lesson.rb:6:in `detect': undefined method `any?' for false:FalseClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/lib/learn_open/lessons.rb:20:in `block in classify'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/lib/learn_open/lessons.rb:19:in `each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/lib/learn_open/lessons.rb:19:in `find'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/lib/learn_open/lessons.rb:19:in `classify'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/lib/learn_open/opener.rb:36:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/lib/learn_open/opener.rb:11:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.21/bin/learn-open:7:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-open:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-open:23:in `<main>'

**Comment by Dalynn4** [comment]
In fact this appears for every lesson that is a code-along for this section in redux. Please also check those if available.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Dalynn4 .

We have updated the materials in this lesson as well as the following code-alongs in this section and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
